### ISSUE TITLE
proof-of-reserves

### ISSUE THREAD

**Issue by Chantaboth** [BitgetLimited/proof-of-reserves#107]
572071e76f5eebe74629cbf82fe3e76a5f664a712e9ee6e3830673123c20db56
f6x37kw3mirlm9qtqr120ac6z3ex7rq0l4fs6fgy25pok8gdfogr5sy52wvtb8ze
572071e76f5eebe74629cbf82fe3e76a5f664a712e9ee6e3830673123c20db56,f6x37kw3mirlm9qtqr120ac6z3ex7rq0l4fs6fgy25pok8gdfogr5sy52wvtb8ze,{"BTC":0,"ETH":0,"USDT":8.72197277,"USDC":0}
72f427b4f7e6ded7

**Comment by Jayydey** [comment]
I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. Please write us back using our “Chat Support” icon located on our [Specter Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by apalos2024** [comment]
Nice
